# Generated by Django 5.2 on 2025-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelesscities',
            name='proportion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
